language: java
jdk:
  - oraclejdk8
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - pip install --user codecov    #Install codecov
after_success:
    - codecov                       #Run codecov
    - bash <(curl -s https://codecov.io/bash)
